#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
rm -r processor*
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
decomposePar
mpirun -np 8 simpleFoam -parallel >log &
#------------------------------------------------------------------------------
